Class PerimeterInfo
{
	int l=20;
	int b=7;
int p=2*(l+b);
}


class Perimeter 
{
	public static void main(String[] args) 
	{
		System.out.println("Start Of Java Code");
		PerimeterInfo ref=new PerimeterInfo();
		System.out.println("Length is"+new Perimeterinfo().l);
		System.out.println("Breadth is"+new Perimeterinfo().b);
		System.out.println("Perimeter is"+new Perimeterinfo().p);
		ref.l=10;
		ref.b=12;
		ref.p=24;
		System.out.println(" New Length is"+ref.l);
		System.out.println("New Breadth is"+ref.b);
		System.out.println("Perimeter is"+ref.p);
		System.out.println("End Of Java Code"); 







	}
}